---

# This compose file acts as an example on using docker volumes for nagios
# configuration. As nagios configurations are different for each site they are
# not considered part of the container image. The best way to deal with the
# configurations is to store them in a volume allowing the user to upgrade the
# image without the need to extract the site configuration from the container.

version: '3'
services:
  nagios:
    image: jasonrivers/nagios:latest
    ports:
    - "8080:80"
    volumes:
    - nagiosetc:/opt/nagios/etc
    - nagiosvar:/opt/nagios/var
    - customplugins:/opt/Custom-Nagios-Plugins
    - nagiosgraphvar:/opt/nagiosgraph/var
    - nagiosgraphetc:/opt/nagiosgraph/etc

volumes:
    nagiosetc:
    nagiosvar:
    customplugins:
    nagiosgraphvar:
    nagiosgraphetc:
# TAGGED: 2025-04-13T13:10:17.547669874+07:00