#!/usr/bin/env bash

update=false
pushlock=false
reevaluate=false
showtrace=false

# Parse command-line arguments
while [ "$1" != "" ]; do
    case $1 in
        --update ) update=true ;;
        --pushlock ) pushlock=true ;;
        --force-evaluate ) reevaluate=true ;;
        --show-trace ) showtrace=true ;;
        * )        ;;
    esac
    shift
done

if [ "$reevaluate" = true ]; then
    echo " " >> ~/.nixcfg/flake.nix
fi

if [[ "$(uname)" == "Linux" ]]; then
    echo "Running on Linux"
    # Linux-specific commands here

    # Push flake.lock if requested
    # useful to revert to a previous lock file
    echo "*** Pushing flake.lock."
    sudo cp ~/.nixcfg/flake.lock /etc/nixos/flake.lock

    sudo rsync -ahi --delete --recursive --exclude ".stfolder" --exclude '*.lock' --exclude '.git' --exclude 'bootstrap.sh' --exclude '.gitignore' --exclude 'sync' --exclude 'dump.sh'  ~/.nixcfg/ /etc/nixos/
  
    # Update flakes if requested
    if [ "$update" = true ]; then
        echo "Updating flakes..."
        pushd /etc/nixos
        sudo nix flake update
        popd
    fi

    if [ "$showtrace" = true ]; then
        sudo nixos-rebuild switch --show-trace
    else
        sudo nixos-rebuild switch
    fi

    echo "*** Pulling flake.lock."
    sudo cp /etc/nixos/flake.lock ~/.nixcfg/
    sudo chown -R "$USER":users ~/.nixcfg/flake.lock
    sudo chmod -R 664 ~/.nixcfg/flake.lock
elif [[ "$(uname)" == "Darwin" ]]; then
    echo "Running on macOS"

    echo "*** Pushing flake.lock."
    sudo cp ~/.nixcfg/flake.lock ~/.config/nix/flake.lock

    sudo rsync -ahi --delete --recursive --exclude ".stfolder" --exclude '*.lock' --exclude '.git' --exclude 'bootstrap.sh' --exclude '.gitignore' --exclude 'sync' --exclude 'dump.sh'  ~/.nixcfg/ ~/.config/nix

    if [ "$update" = true ]; then
        echo "Updating flakes..."
        nix flake update
    fi

    if [ "$showtrace" = true ]; then
        darwin-rebuild switch --flake ~/.config/nix --show-trace
    else
        darwin-rebuild switch --flake ~/.config/nix
    fi

    echo "*** Pulling flake.lock."
    cp ~/.config/nix/flake.lock ~/.nixcfg/flake.lock
fi

# reload .zshrc to immediately reflect any shell changes
source ~/.zshrc
unset __HM_SESS_VARS_SOURCED
source ~/.zshenv
