services:
  grampsweb: &grampsweb
    image: ghcr.io/gramps-project/grampsweb:latest
    restart: always
    ports:
      - "8888:5000"  # host:docker
    environment:
      GRAMPSWEB_TREE: "Gramps Web"  # will create a new tree if not exists
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
    depends_on:
      - grampsweb_redis
    volumes:
      - gramps_users:/app/users  # persist user database
      - gramps_index:/app/indexdir  # persist search index
      - gramps_thumb_cache:/app/thumbnail_cache  # persist thumbnails
      - gramps_cache:/app/cache  # persist export and report caches
      - gramps_secret:/app/secret  # persist flask secret
      - gramps_db:/root/.gramps/grampsdb  # persist Gramps database
      - gramps_media:/app/media  # persist media files
      - gramps_tmp:/tmp

  grampsweb_celery:
    <<: *grampsweb  # YAML merge key copying the entire grampsweb service config
    ports: []
    # container_name: grampsweb_celery
    depends_on:
      - grampsweb_redis
    command: celery -A gramps_webapi.celery worker --loglevel=INFO

  grampsweb_redis:
    image: docker.io/library/redis:7.2.4-alpine
    container_name: grampsweb_redis
    restart: always

volumes:
  gramps_users:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tank/containers/gramps/users
  gramps_index:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tank/containers/gramps/index
  gramps_thumb_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tank/containers/gramps/thumb_cache
  gramps_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tank/containers/gramps/cache
  gramps_secret:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tank/containers/gramps/secret
  gramps_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tank/containers/gramps/db
  gramps_media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tank/containers/gramps/media
  gramps_tmp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tank/containers/gramps/tmp
# TAGGED: 2024-09-30T13:40:13.801524109+07:00