apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: nagiosvar
  name: nagiosvar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
