apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o nagios
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: nagios
  name: nagios
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nagios
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o nagios
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/nagios-default: "true"
        io.kompose.service: nagios
    spec:
      containers:
        - image: jasonrivers/nagios:latest
          name: nagios
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/nagios/etc
              name: nagiosetc
            - mountPath: /opt/nagios/var
              name: nagiosvar
            - mountPath: /opt/Custom-Nagios-Plugins
              name: customplugins
            - mountPath: /opt/nagiosgraph/var
              name: nagiosgraphvar
            - mountPath: /opt/nagiosgraph/etc
              name: nagiosgraphetc
      restartPolicy: Always
      volumes:
        - name: nagiosetc
          persistentVolumeClaim:
            claimName: nagiosetc
        - name: nagiosvar
          persistentVolumeClaim:
            claimName: nagiosvar
        - name: customplugins
          persistentVolumeClaim:
            claimName: customplugins
        - name: nagiosgraphvar
          persistentVolumeClaim:
            claimName: nagiosgraphvar
        - name: nagiosgraphetc
          persistentVolumeClaim:
            claimName: nagiosgraphetc
