apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: nagiosgraphvar
  name: nagiosgraphvar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
