apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o nagios
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: nagios
  name: nagios
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    io.kompose.service: nagios
