# .sops.yaml
keys:
  - &admin_aaronp age1r8x64pvspkksr490yeam2xcxe98xne3n3jly4ey5g48500x57cpq8c5w7u
  - &server_yggdrasil age1uc4q83ys5tgm2sxvxuyusmx7r0fxgn359ujlh0kfqfs23lrmrvgs2tz5zn
  - &container_garage age18y2k5u875kg8zkhu3d4x9u3m8wvmc86a66fgln4um6pf92swe52s5fafxy
creation_rules:
  - path_regex: system-yggdrasil.yaml$
    key_groups:
      - age:
          - *server_yggdrasil
          - *admin_aaronp
  - path_regex: admin-aaronp.yaml$
    key_groups:
      - age:
          - *admin_aaronp
  - path_regex: container-garage.yaml$
    key_groups:
      - age:
          - *admin_aaronp
          - *container_garage
