# .sops.yaml
keys:
  - &admin_aaronp age1r8x64pvspkksr490yeam2xcxe98xne3n3jly4ey5g48500x57cpq8c5w7u
  - &admin_aaronp_geth age1j58hzvxqsv8gwfrmdaqn34k54vyp4k86u0nwwr5hszgv4s8vscfqznsvd4
  - &server_yggdrasil age1uc4q83ys5tgm2sxvxuyusmx7r0fxgn359ujlh0kfqfs23lrmrvgs2tz5zn
  - &container_garage age18y2k5u875kg8zkhu3d4x9u3m8wvmc86a66fgln4um6pf92swe52s5fafxy
  - &container_n8n age1mmaxq53q6us0g70mq0p0md6vr00arjkp62l6dgeavhr7urfjm3tqvt46nt
  - &container_copyparty age14c33tehzfx77kraxh2hzl8uymjh9tjmnh0npmu9gxwn7vew7heeqre00gn
  - &container_matrix age13j8v6l494q7z8ykqv6etzutuecvgkdh97zz66azyzrqgnlp935ws6hurdx
creation_rules:
  - path_regex: system-yggdrasil.yaml$
    key_groups:
      - age:
          - *server_yggdrasil
          - *admin_aaronp
          - *admin_aaronp_geth
  - path_regex: admin-aaronp.yaml$
    key_groups:
      - age:
          - *admin_aaronp
          - *admin_aaronp_geth
  - path_regex: container-garage.yaml$
    key_groups:
      - age:
          - *admin_aaronp
          - *admin_aaronp_geth
          - *container_garage
  - path_regex: container-n8n.yaml$
    key_groups:
      - age:
          - *admin_aaronp
          - *admin_aaronp_geth
          - *container_n8n
  - path_regex: container-copyparty.yaml$
    key_groups:
      - age:
          - *admin_aaronp
          - *admin_aaronp_geth
          - *container_copyparty
  - path_regex: container-matrix.yaml$
    key_groups:
      - age:
          - *admin_aaronp
          - *admin_aaronp_geth
          - *container_matrix
