# Auto-generated using compose2nix v0.2.3-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };
  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."babybuddy" = {
    image = "lscr.io/linuxserver/babybuddy";
    environment = {
      "TZ" = "UTC";
    };
    volumes = [
      "/tank/containers/babybuddy/config:/config:rw"
    ];
    ports = [
      "11606:8000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=babybuddy"
      "--network=babybuddy_default"
    ];
  };
  systemd.services."podman-babybuddy" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
    };
    after = [
      "podman-network-babybuddy_default.service"
    ];
    requires = [
      "podman-network-babybuddy_default.service"
    ];
    partOf = [
      "podman-compose-babybuddy-root.target"
    ];
    wantedBy = [
      "podman-compose-babybuddy-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-babybuddy_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f babybuddy_default";
    };
    script = ''
      podman network inspect babybuddy_default || podman network create babybuddy_default
    '';
    partOf = [ "podman-compose-babybuddy-root.target" ];
    wantedBy = [ "podman-compose-babybuddy-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-babybuddy-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
