services:
  suggestarr:
    image: ciuse99/suggestarr:latest
    container_name: SuggestArr
    restart: always
    network_mode: host
    # ports:
    #   - "5000:5000"
    volumes:
      - /tank/containers/suggestarr/config_files:/app/config/config_files
# TAGGED: 2025-04-13T13:10:17.547669874+07:00