services:
  whisparr:
    container_name: whisparr
    network_mode: host
    image: ghcr.io/hotio/whisparr
    ports:
      - "6969:6969"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Jakarta
    volumes:
      - /mnt/bigboy/docker/whisparr/config:/config
      - /mnt/bigboy/docker/whisparr/data:/data
      - /mnt/bigboy/media/naughty:/mnt/naughty
