[[language]]
name = "rust"
auto-format = true

[[language]]
name = "nix"
auto-format = true
file-types = [ "nix" ]
language-servers = [ "rnix-lsp" ]
formatter = { command = "nixpkgs-fmt", args = [] }
