# .sops.yaml
keys:
    - &admin_aaronp age1r8x64pvspkksr490yeam2xcxe98xne3n3jly4ey5g48500x57cpq8c5w7u
    - &server_yggdrasil age1uc4q83ys5tgm2sxvxuyusmx7r0fxgn359ujlh0kfqfs23lrmrvgs2tz5zn
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *server_yggdrasil
          - *admin_aaronp
